### PR TITLE
Feature/example DSLs for multi metamodels

### PR DESCRIPTION
**Pull request by goto40**
Here, we have an inital version of some **example DSLs**. **Details/challanges**: see examples/multimetamodel/README.md: The **goal** is
 
  * to show how to **setup textX DSL projects** (focus: multi metamodels), and
  * to show how to **integrate textX DSLs into textX-LS**.

**Note**: at the moment no language template or similar has been applied. I am willing to change this, but I like to get some first feedback, the I can adapt according to comments.

**Comments welcome!** (Commit history is a mess; we can squash all commits into one when merging).

### CODE REVIEW

**Comment by igordejanovic** [comment]
@goto40 Great work Pierre!

This is an excellent example, perfectly balanced to span many features but still remains small enough to be easy to grasp.

I think that this example, as it is a full-blown set of projects, deserves a separate git repo. Just tell me the name of the repo and I'll create it. Than we can reference it from both textX and textX-LS docs and READMEs.

Here are some notes (we can continue in the new repo afterwards):
- I would like for `validate...` CLI commands to be registered as textX CLI extensions `textx validate ...`. If made generic enough `validate` subcommand might move to the textX project and specific validators could be registered at a new entry point analyzed by `validate` subcommand.
- I like `challenges  for an editor` sections. Those should help @danixeee to test LS and VS Code extensions. After that work is finished we could update those sections to explain how LS and the editor supports those features.

**Comment by danixeee** [comment]
@goto40 Great work and thank you for this.

I haven't had much time to go through examples yet, but I will within a few days. If we create a separate repo, we can try to follow language template and add a support for _textX-LS_. Maybe it makes sense to create a separate branch for _textX-LS_ support and keep work there, then we can reference that branch from _textX-LS_ docs, if we don't want to mix things.

**Comment by goto40** [comment]
Let's call the new project 'examples_multi_metamodel'?

Or is it possible to make subfolders: 'examples/multi_metamodel'?

**Comment by goto40** [comment]
You are welcome. It is a pleasure to participate to textX!

**Comment by igordejanovic** [comment]
@goto40 I've just created `textx-multi-metamodel-example` project and you are the admin/maintainer ;)
When you set it up we'll link from the docs. It'll be featured as a complete project with multiple languages/generators/models so that users could clone the project and use it as the base for their development. 

I guess it's perfectly fine for the example to be complete with textX-LS stuff as textX-LS will be officially supported. No need to complicate with separate branches.

**Comment by goto40** [comment]
Moved to https://github.com/textX/textx-multi-metamodel-example/pull/1

**Pull request closed without merging**
